import os
import sys
import json
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
)
from reportlab.pdfgen import canvas

class NumberedCanvas(canvas.Canvas):
    def __init__(self, *args, **kwargs):
        super(NumberedCanvas, self).__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_number(num_pages)
            super(NumberedCanvas, self).showPage()
        super(NumberedCanvas, self).save()

    def draw_page_number(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 9)
        self.setFillColor(colors.HexColor("#64748B"))
        
        # Header (pages > 1)
        if self._pageNumber > 1:
            self.drawString(54, 11 * inch - 36, "ANKA SPHERE — Monthly Content Performance Report")
            self.setStrokeColor(colors.HexColor("#E2E8F0"))
            self.setLineWidth(0.5)
            self.line(54, 11 * inch - 42, 8.5 * inch - 54, 11 * inch - 42)
            
        # Footer
        page_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(8.5 * inch - 54, 36, page_text)
        self.drawString(54, 36, "CONFIDENTIAL — GENERATED BY ANKA SPHERE OPERATIONS")
        self.setStrokeColor(colors.HexColor("#E2E8F0"))
        self.setLineWidth(0.5)
        self.line(54, 48, 8.5 * inch - 54, 48)
        
        self.restoreState()

def build_report_pdf(json_path, pdf_path):
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    doc = SimpleDocTemplate(
        pdf_path,
        pagesize=letter,
        leftMargin=54,
        rightMargin=54,
        topMargin=54,
        bottomMargin=54
    )
    
    styles = getSampleStyleSheet()
    
    # Custom Palette (matching the operations dashboard brand)
    PRIMARY = colors.HexColor("#0F172A")    # Deep Slate
    ACCENT = colors.HexColor("#F59E0B")     # Warm Amber (Content Marketing theme color)
    TEXT_DARK = colors.HexColor("#1E293B")
    TEXT_MUTED = colors.HexColor("#64748B")
    BG_LIGHT = colors.HexColor("#F8FAFC")
    BORDER_COLOR = colors.HexColor("#E2E8F0")

    # Typography Styles
    styles.add(ParagraphStyle(
        'DocTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=24,
        leading=28,
        textColor=PRIMARY,
        spaceAfter=4
    ))

    styles.add(ParagraphStyle(
        'DocSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=12,
        leading=16,
        textColor=TEXT_MUTED,
        spaceAfter=15
    ))

    styles.add(ParagraphStyle(
        'SectionHeader',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=14,
        leading=18,
        textColor=PRIMARY,
        spaceBefore=14,
        spaceAfter=8,
        keepWithNext=True
    ))

    styles.add(ParagraphStyle(
        'CustomBody',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9.5,
        leading=14,
        textColor=TEXT_DARK
    ))

    styles.add(ParagraphStyle(
        'CustomBodyBold',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=9.5,
        leading=14,
        textColor=TEXT_DARK
    ))

    styles.add(ParagraphStyle(
        'TableHeader',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=9,
        leading=12,
        textColor=colors.white
    ))

    story = []

    # Title & Header Block
    story.append(Paragraph("Monthly Content Performance Report", styles['DocTitle']))
    story.append(Paragraph(f"Project: <b>{data.get('projectName', 'N/A')}</b> &nbsp;·&nbsp; Client: <b>{data.get('clientName', 'N/A')}</b> &nbsp;·&nbsp; Period: <b>{data.get('period', 'N/A')}</b>", styles['DocSubtitle']))
    
    story.append(HRFlowable(width="100%", thickness=1.5, color=ACCENT, spaceBefore=0, spaceAfter=15))

    # Executive Overview
    story.append(Paragraph("1. Content Production Summary", styles['SectionHeader']))
    story.append(Paragraph(
        f"This report outlines content creation, email nurture stats, and Organic Growth performance metrics "
        f"for <b>{data.get('projectName')}</b> during the month of <b>{data.get('period')}</b>. "
        f"A total of <b>{data['stats'].get('totalProduced', 0)}</b> content pieces were finalized and distributed "
        f"across all sub-departments (Blogs, Social media channels, and Email newsletter workflows).",
        styles['CustomBody']
    ))
    story.append(Spacer(1, 10))

    # Stats Table
    stats_data = [
        [
            Paragraph("<b>Total Produced</b>", styles['CustomBody']),
            Paragraph("<b>Blog Posts</b>", styles['CustomBody']),
            Paragraph("<b>Social Posts</b>", styles['CustomBody']),
            Paragraph("<b>Email Newsletters</b>", styles['CustomBody'])
        ],
        [
            Paragraph(f"<font size=14 color='#0F172A'><b>{data['stats'].get('totalProduced', 0)}</b></font>", styles['CustomBody']),
            Paragraph(f"<font size=14 color='#F59E0B'><b>{data['stats'].get('blogsProduced', 0)}</b></font>", styles['CustomBody']),
            Paragraph(f"<font size=14 color='#10B981'><b>{data['stats'].get('socialsProduced', 0)}</b></font>", styles['CustomBody']),
            Paragraph(f"<font size=14 color='#3B82F6'><b>{data['stats'].get('emailsProduced', 0)}</b></font>", styles['CustomBody'])
        ]
    ]
    
    stats_table = Table(stats_data, colWidths=[1.75 * inch, 1.75 * inch, 1.75 * inch, 1.75 * inch])
    stats_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), BG_LIGHT),
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('BOX', (0,0), (-1,-1), 0.5, BORDER_COLOR),
        ('INNERGRID', (0,0), (-1,-1), 0.5, BORDER_COLOR),
        ('PADDING', (0,0), (-1,-1), 10),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
    ]))
    story.append(stats_table)
    story.append(Spacer(1, 15))

    # Top Articles Section
    story.append(Paragraph("2. Top Performing Articles (GA4 & organic)", styles['SectionHeader']))
    story.append(Paragraph("Analytics capturing organic reader acquisition, session depth, and average engagement times by page title:", styles['CustomBody']))
    story.append(Spacer(1, 8))

    articles_table_data = [
        [
            Paragraph("Article / Page Title", styles['TableHeader']),
            Paragraph("Path / Slug", styles['TableHeader']),
            Paragraph("Organic Views", styles['TableHeader']),
            Paragraph("Avg. Engagement Time", styles['TableHeader'])
        ]
    ]

    for art in data.get('topArticles', []):
        articles_table_data.append([
            Paragraph(art.get('title', 'N/A'), styles['CustomBodyBold']),
            Paragraph(f"/{art.get('slug', '')}", styles['CustomBody']),
            Paragraph(f"{art.get('views', 0):,}", styles['CustomBody']),
            Paragraph(art.get('engagementTime', 'N/A'), styles['CustomBody'])
        ])

    art_table = Table(articles_table_data, colWidths=[2.6 * inch, 1.8 * inch, 1.2 * inch, 1.4 * inch])
    art_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), PRIMARY),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('BOX', (0,0), (-1,-1), 0.5, BORDER_COLOR),
        ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, BG_LIGHT]),
        ('INNERGRID', (0,0), (-1,-1), 0.5, BORDER_COLOR),
        ('PADDING', (0,0), (-1,-1), 8),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
    ]))
    story.append(art_table)
    story.append(Spacer(1, 15))

    # Email & Traffic Contribution
    story.append(Paragraph("3. Channel Performance & Growth Contribution", styles['SectionHeader']))
    
    contrib = data.get('trafficContribution', {})
    emails = data.get('emailMetrics', {})
    
    channel_data = [
        [
            Paragraph("<b>Email Marketing Performance</b>", styles['CustomBodyBold']),
            Paragraph("<b>Site Traffic Contribution</b>", styles['CustomBodyBold'])
        ],
        [
            Paragraph(
                f"Campaigns Sent: <b>{emails.get('campaignsSent', 0)}</b><br/>"
                f"Audience Reached: <b>{emails.get('audienceReached', 0):,} subscribers</b><br/>"
                f"Average Open Rate: <b>{emails.get('openRate', 'N/A')}</b><br/>"
                f"Average Click-Through Rate: <b>{emails.get('clickRate', 'N/A')}</b>",
                styles['CustomBody']
            ),
            Paragraph(
                f"Organic Content Sessions: <b>{contrib.get('contentSessions', 0):,}</b><br/>"
                f"Total Overall Site Sessions: <b>{contrib.get('totalSessions', 0):,}</b><br/>"
                f"Growth Traffic Contribution: <b>{contrib.get('percentage', 'N/A')}</b>",
                styles['CustomBody']
            )
        ]
    ]
    
    chan_table = Table(channel_data, colWidths=[3.5 * inch, 3.5 * inch])
    chan_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), BG_LIGHT),
        ('BOX', (0,0), (-1,-1), 0.5, BORDER_COLOR),
        ('INNERGRID', (0,0), (-1,-1), 0.5, BORDER_COLOR),
        ('PADDING', (0,0), (-1,-1), 10),
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
    ]))
    story.append(chan_table)
    story.append(Spacer(1, 15))

    # Content Pillars Distribution
    if data.get('pillars'):
        story.append(Paragraph("4. Content Pillars Balance", styles['SectionHeader']))
        story.append(Paragraph("Distribution of content produced across established brand content pillars:", styles['CustomBody']))
        story.append(Spacer(1, 8))

        pillar_table_data = [
            [
                Paragraph("Content Pillar Theme", styles['TableHeader']),
                Paragraph("Pieces Tagged", styles['TableHeader']),
                Paragraph("Pillar Coverage Share", styles['TableHeader'])
            ]
        ]
        
        total_p = sum(p.get('count', 0) for p in data.get('pillars', [])) or 1
        for pil in data.get('pillars', []):
            count = pil.get('count', 0)
            share = f"{(count / total_p) * 100:.1f}%"
            pillar_table_data.append([
                Paragraph(pil.get('name', 'N/A'), styles['CustomBodyBold']),
                Paragraph(str(count), styles['CustomBody']),
                Paragraph(share, styles['CustomBody'])
            ])

        pil_table = Table(pillar_table_data, colWidths=[3.2 * inch, 1.8 * inch, 2.0 * inch])
        pil_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), PRIMARY),
            ('ALIGN', (0,0), (-1,-1), 'LEFT'),
            ('BOX', (0,0), (-1,-1), 0.5, BORDER_COLOR),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, BG_LIGHT]),
            ('INNERGRID', (0,0), (-1,-1), 0.5, BORDER_COLOR),
            ('PADDING', (0,0), (-1,-1), 8),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ]))
        story.append(pil_table)

    # Build the document
    doc.build(story, canvasmaker=NumberedCanvas)

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python generate_content_report.py <input_json> <output_pdf>")
        sys.exit(1)
    build_report_pdf(sys.argv[1], sys.argv[2])
    print("Content report PDF successfully built.")
